- hosts: servers
  become: true
  # become_method: sudo
  # become_user: root
  # become_ask_pass: false
  gather_facts: no
  tasks:
  - name: copy manifest files to kube-master
    copy:
      src: ./deployment.yml
      dest: /ansible/

  - name: Delete the previous of kubernetes objects
    shell: kubectl apply -f /ansible/deployment.yml

  - name: Deploy manifest on Kubernetes
    shell: kubectl apply -f /ansible/deployment.yml