---
- hosts: servers
  become: yes
  become_user: ubuntu
  become_method: su
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /ubuntu/demo-xyz
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0744'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /ubuntu/demo-xyz/Dockerfile
        owner: ubuntu
        group: ubuntu
        mode: '0744'
    - name: build container image
      docker_image:
        name: ngwaabanjong/xyz-app
        build:
          path: /ubuntu/demo-xyz
          source: build
        state: present