---
- hosts: servers
  become: true
  become_ask_pass: false
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /ansible/demo-xyz
        state: directory
        owner: ansible
        group: ansible
        mode: '0744'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /ansible/demo-xyz/Dockerfile
        owner: ansible
        group: ansible
        mode: '0744'
    - name: build container image
      docker_image:
        name: ngwaabanjong/xyz-app
        build:
          path: /ansible/demo-xyz
          source: build
        state: present