- hosts: servers
  become: true
  gather_facts: no
  tasks:
  - name: include vault
    ansible.builtin.debug:
      file: mypassword.yml
  - name: print variable
    ansible.builtin.debug:
      var: mypassword
  - name: copy manifest files to kube-master
    copy:
      src: ./deployment.yml
      dest: /ansible/

  - name: Delete the previous of kubernetes objects
    shell: kubectl apply -f /ansible/deployment.yml

  - name: Deploy manifest on Kubernetes
    shell: kubectl apply -f /ansible/deployment.yml