---
- hosts: servers
  become: true
  become_user: ansible
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /home/ansible/demo-xyz
        state: directory
        owner: ansible
        group: ansible
        mode: '0777'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /home/ansible/demo-xyz/Dockerfile
        owner: ansible
        group: ansible
        mode: '0777'
    - name: build container image
      docker_image:
        name: ngwaabanjong/xyz-app
        build:
          path: /home/ansible/demo-xyz
          source: build
        state: present