---
- hosts: servers
  become: true
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /root/demo-xyz
        state: directory
        # owner: root
        # group: root
        mode: '0777'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /root/demo-xyz/Dockerfile
        # owner: root
        # group: root
        mode: '0777'
    - name: build container image
      docker_image:
        name: ngwaabanjong/xyz-app
        build:
          path: /root/demo-xyz
          source: build
        state: present