- hosts: servers
  gather_facts: no
  tasks:
  - name: create detination file
    file:
      path: /home/ansible/
      state: directory
      owner: ansible
      mode: '0777'
  - name: copy manifest files to kube-master
    copy:
      src: ./deployment.yml
      dest: /home/ansible/


  - name: Deploy manifest on Kubernetes
    shell: kubectl apply -k /home/ansible/deployment.yml